version: '2'
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=accounts
    depends_on:
      - db

  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts
      MYSQL_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
